export const SET_STATE = "SET_STATE";
export const RUN_ANALYSIS = "RUN_ANALYSIS";
export const START_SERVER = "START_SERVER";
export const STOP_SERVER = "STOP_SERVER";
export const CANCEL_SOLUTION = "CANCEL_SOLUTION";
export const GET_SOLUTION = "GET_SOLUTION";
export const OPEN_FILE = "OPEN_FILE";
export const VIEW_FIX = "VIEW_FIX";
export const APPLY_FILE = "APPLY_FILE";
export const DISCARD_FILE = "DISCARD_FILE";
export const WEBVIEW_READY = "WEBVIEW_READY";
export const GET_SOLUTION_WITH_KONVEYOR_CONTEXT = "GET_SOLUTION_WITH_KONVEYOR_CONTEXT";
export const CONFIGURE_LABEL_SELECTOR = "CONFIGURE_LABEL_SELECTOR";
export const CONFIGURE_SOURCES_TARGETS = "CONFIGURE_SOURCES_TARGETS";
export const OVERRIDE_ANALYZER_BINARIES = "OVERRIDE_ANALYZER_BINARIES";
export const OPEN_GENAI_SETTINGS = "OPEN_GENAI_SETTINGS";
export const CONFIGURE_CUSTOM_RULES = "CONFIGURE_CUSTOM_RULES";
export const OVERRIDE_RPC_SERVER_BINARIES = "OVERRIDE_RPC_SERVER_BINARIES";

export type WebviewActionType =
  | typeof SET_STATE
  | typeof RUN_ANALYSIS
  | typeof START_SERVER
  | typeof STOP_SERVER
  | typeof CANCEL_SOLUTION
  | typeof GET_SOLUTION
  | typeof OPEN_FILE
  | typeof VIEW_FIX
  | typeof APPLY_FILE
  | typeof DISCARD_FILE
  | typeof WEBVIEW_READY
  | typeof GET_SOLUTION_WITH_KONVEYOR_CONTEXT
  | typeof CONFIGURE_LABEL_SELECTOR
  | typeof CONFIGURE_SOURCES_TARGETS
  | typeof OVERRIDE_ANALYZER_BINARIES
  | typeof OVERRIDE_RPC_SERVER_BINARIES
  | typeof OPEN_GENAI_SETTINGS
  | typeof CONFIGURE_CUSTOM_RULES
  | typeof WEBVIEW_READY;

export interface WebviewAction<S, T> {
  type: S;
  payload: T;
}
