export const SET_STATE = "SET_STATE";
export const RUN_ANALYSIS = "RUN_ANALYSIS";
export const START_SERVER = "START_SERVER";
export const STOP_SERVER = "STOP_SERVER";
export const RESTART_SOLUTION_SERVER = "RESTART_SOLUTION_SERVER";
export const CANCEL_SOLUTION = "CANCEL_SOLUTION";
export const GET_SOLUTION = "GET_SOLUTION";
export const GET_SUCCESS_RATE = "GET_SUCCESS_RATE";
export const OPEN_FILE = "OPEN_FILE";
export const VIEW_FIX = "VIEW_FIX";
export const WEBVIEW_READY = "WEBVIEW_READY";
export const GET_SOLUTION_WITH_KONVEYOR_CONTEXT = "GET_SOLUTION_WITH_KONVEYOR_CONTEXT";
export const CONFIGURE_LABEL_SELECTOR = "CONFIGURE_LABEL_SELECTOR";
export const CONFIGURE_SOURCES_TARGETS = "CONFIGURE_SOURCES_TARGETS";
export const OVERRIDE_ANALYZER_BINARIES = "OVERRIDE_ANALYZER_BINARIES";
export const OPEN_GENAI_SETTINGS = "OPEN_GENAI_SETTINGS";
export const CONFIGURE_CUSTOM_RULES = "CONFIGURE_CUSTOM_RULES";
export const OVERRIDE_RPC_SERVER_BINARIES = "OVERRIDE_RPC_SERVER_BINARIES";
export const SET_ACTIVE_PROFILE = "SET_ACTIVE_PROFILE";
export const OPEN_PROFILE_MANAGER = "OPEN_PROFILE_MANAGER";
export const ADD_PROFILE = "ADD_PROFILE";
export const DELETE_PROFILE = "DELETE_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const QUICK_RESPONSE = "QUICK_RESPONSE";
export const OPEN_FILE_IN_EDITOR = "OPEN_FILE_IN_EDITOR";
export const TOGGLE_AGENT_MODE = "TOGGLE_AGENT_MODE";

export type WebviewActionType =
  | typeof SET_STATE
  | typeof RUN_ANALYSIS
  | typeof START_SERVER
  | typeof STOP_SERVER
  | typeof RESTART_SOLUTION_SERVER
  | typeof CANCEL_SOLUTION
  | typeof GET_SOLUTION
  | typeof GET_SUCCESS_RATE
  | typeof OPEN_FILE
  | typeof VIEW_FIX
  | typeof WEBVIEW_READY
  | typeof GET_SOLUTION_WITH_KONVEYOR_CONTEXT
  | typeof CONFIGURE_LABEL_SELECTOR
  | typeof CONFIGURE_SOURCES_TARGETS
  | typeof OVERRIDE_ANALYZER_BINARIES
  | typeof OVERRIDE_RPC_SERVER_BINARIES
  | typeof OPEN_GENAI_SETTINGS
  | typeof CONFIGURE_CUSTOM_RULES
  | typeof WEBVIEW_READY
  | typeof SET_ACTIVE_PROFILE
  | typeof ADD_PROFILE
  | typeof DELETE_PROFILE
  | typeof UPDATE_PROFILE
  | typeof OPEN_PROFILE_MANAGER
  | typeof QUICK_RESPONSE
  | typeof OPEN_FILE_IN_EDITOR
  | typeof TOGGLE_AGENT_MODE;
export interface WebviewAction<S, T> {
  type: S;
  payload: T;
}
